### ISSUE TITLE
Names including "With" parse out to acquisition method "With"

### ISSUE THREAD

**Issue by BergFulton** [cmoa/elysa#83]
For example see IRN 1003731

"Gift of Mrs. Virginia *Witherow* Ahlbrandt" becomes 

"with Virginia eroe, 1998". 

I tried it with names like "Withheld" and "Withfield" and the same thing happens.

**Comment by workergnome** [comment]
Dang it.  Thought I'd fixed that one.

**Comment by workergnome** [comment]
Fixed.  Re-pull the museum_provenance library.

**Comment by BergFulton** [comment]
Sweet, thanks.
[cid:image001.jpg@01D0BB1C.17378FA0]

Tracey Berg-Fulton, M.Litt.
Collections Database Associate
Carnegie Museum of Art
4400 Forbes Avenue
Pittsburgh, PA 15213
Berg-FultonT@cmoa.org
412.622.6509
